name: Update dataset repos
on:
  push:
    branches:
      - 'main'
jobs:
  update-dataset-repo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fork:
          - neurodatascience/mini_proc-ppmi
          - neurodatascience/mini_proc-qpn
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ matrix.fork }}
      - name: Get upstream changes
        run: |
          git remote add upstream https://github.com/neurodatascience/mini_proc.git
          git fetch upstream main:upstream-main
          git reset --hard upstream-main
      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v4
        with:
          title: Update to match `neurodatascience/mr_proc:main`
          body: PR created by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action.
          labels: auto-pr
          token: ${{ secrets.PAT }}
          branch: upstream-changes
      - name: Approve Pull Request
        if: ${{ steps.create-pr.outputs.pull-request-number }}
        uses: juliangruber/approve-pull-request-action@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.create-pr.outputs.pull-request-number }}
          repo: ${{ matrix.fork }}
#         uses: michellewang/auto-approve-action@v3
#         with:
#           repository: ${{ matrix.fork }}
#           pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
#           review-message: Auto-approved by GitHub action.
#           github-token: ${{ secrets.PAT }}
        
