name: Update dataset repos
on:
  push:
    branches:
      - 'main'
jobs:
  update-dataset-repo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fork:
          - neurodatascience/mini_proc-ppmi
          - neurodatascience/mini_proc-qpn
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ matrix.fork }}
      - name: Get upstream changes
        run: |
          git remote add upstream https://github.com/neurodatascience/mini_proc.git
          git fetch upstream main:upstream-main
          git reset --hard upstream-main
      - name: Create Pull Request
        id: create-pull-request
        uses: peter-evans/create-pull-request@v4
        with:
          title: Update to match neurodatascience/mr_proc:main
          body: PR created/updated automatically by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action.
          token: ${{ secrets.PAT }}
          branch: main-upstream
          labels: automerge
      - name: Automerge Pull Request
        id: automerge-pull-request
        if: ${{ steps.create-pull-request.outputs.pull-request-number }}
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          MERGE_LABELS: automerge
          MERGE_METHOD: merge
          MERGE_COMMIT_MESSAGE: "{pullRequest.title} (#{pullRequest.number})"
          MERGE_REQUIRED_APPROVALS: 0
          MERGE_DELETE_BRANCH: false
          MERGE_ERROR_FAIL: true
          PULL_REQUEST: ${{ matrix.fork }}/${{ steps.create-pull-request.outputs.pull-request-number }}
      - name: Check if success
        if: ${{ steps.automerge-pull-request.outputs.mergeResult != 'merged' }}
        run: |
          echo "Unable to merge pull request #${{ steps.automerge-pull-request.outputs.pullRequestNumber }}"
          exit 1
        
